### ISSUE TITLE
Exceção dentro da função do aluno deve produzir score 0 para o teste em submit_test

### ISSUE THREAD

**Issue by fabiocapsouza** [erickseolin/jn_tester#11]
Este é o comportamento na perftest. Atualmente a exceção não é capturada e o submit é interrompido.

Estou vendo qual é o melhor jeito de resolver isso. Como o aluno executa os testes com Execution.exec_test enquanto está fazendo a função, nessa etapa a exceção não deve ser capturada para indicar o erro. Já no submit_test, o correto seria atribuir score 0 para o teste em que ocorreu exceção.

Pensei em alterar TestSet.evaluate para incluir um parâmetro opcional que ativaria esse funcionamento.
Não sei como ficaria a questão do método performance...

Opiniões?

**Comment by rdenadai** [comment]
Talvez tratar a exception como era feito no perftest mesmo.
Substituir:
https://github.com/erickseolin/jn_tester/blob/master/jn_tester/professor/models.py#L111
```python
[test.performance(function, runs) for test in self]
```

Por algo como:

```python
perfs = []
for test in self:
    try:
        perfs.append(test.performance(function, runs))
    except Exception as err:
        perfs.append({'time': 0., 'memory': 0.})
return perfs
```

**Comment by fabiocapsouza** [comment]
Beleza, farei isso agora

**Comment by erickseolin** [comment]
Mas desse modo não tem como saber que ocorreu uma excessão, como a pessoa vai saber se ela esta calculando errado ou tem um erro na função?

**Comment by fabiocapsouza** [comment]
Em qual situação, Erick? 
Do jeito que eu alterei aqui, a exceção só não é mostrada pra pessoa quando ela enviar os resultados finais com o submit_test. Enquanto ela está usando exec_test durante o desenvolvimento, as exceções não são capturadas.

**Comment by rdenadai** [comment]
Bom isso é verdade também... talvez a melhor opção seja tratar a exception mas ao invés de simplesmente voltar 0. tudo, fazer isso e colocar mensagens de warning.

```python
perfs = []
for test in self:
    try:
        perfs.append(test.performance(function, runs))
    except Exception as err:
        perfs.append({'time': 0., 'memory': 0.})
        warnings.warn('Error: in test cause by {0}'.format(err))
return perfs
```

**Comment by fabiocapsouza** [comment]
Enviei as alterações para o branch fix_11 e fiz merge com o branch develop.
