### ISSUE TITLE
Permitir que o arquivo do aluno grave +1 test

### ISSUE THREAD

**Issue by rdenadai** [erickseolin/jn_tester#12]
O método de submit_test (https://github.com/erickseolin/jn_tester/blob/master/jn_tester/student/test.py#L18) esta gravando o resultado chamando a classe Results.
A classe Results cria o arquivo final, mas sobreescreve o resultado anterior. Este comportamente já havia sido observado pelo @fabiocapsouza em uma troca de emails.

Minha sugestão neste caso é alterar a classe Results, permitindo que ao instanciar a mesma ela carregue a si mesmo como uma lista de resultados (como o gerado pelo script results-generator.py
https://github.com/erickseolin/jn_tester/blob/master/tools/results-generator.py#L83).

**Comment by erickseolin** [comment]
Vou tentar resolver isso.

**Comment by rdenadai** [comment]
Ao salvar, carregar os dados anteriores e ai salvar com tudo. Algo assim talvez.

**Comment by erickseolin** [comment]
Quem está lendo da classe Results? Ela não esta sendo usada para ler o arquivo.

**Comment by rdenadai** [comment]
Hoje, acho que esta lendo dela...  o submit_test esta apenas gravando.
Lá é feito um Results.save...

A sugestão talvez seja reorganizar ela, para que ao instanciar a classe com o nome do teste e path, seja feito um load dos resultados prévios, agregando o resultado atual.
Assim ao dar um save, faz grava os dados antigos com os novos.

Deste modo o método load seria apenas interno a classe, protegido (_load) ou privado (__load).

até

**Comment by rdenadai** [comment]
Érick, o trabalho que você fez na branch resolving_fix_12 está terminado?

Posso validar e testar?

Estou pensando em trabalhar em outro enhancement relacionado a apresentação do DataFrame do pandas... neste caso, iria interferir diretamente no trabalho que você esta fazendo ao resolver este issue.

**Comment by erickseolin** [comment]
Oi Rodolfo,

ainda não terminei. Não tive tempo de trabalhar no projeto neste fim de semana.
Mas nesse commit que fiz a base do novo Results está pronta. A ideia é so poder ler os dados guardados através dela. Assim a aquisição dos dados não fica no código de visualização, que deve usar o Results ou ResultsScanner para ler os dados.

Se quiser pode fazer um branch desse resolving_fix_12 para fazer suas mudanças, acho que ele estava funcionando já, so ia fazer algumas melhorias no código.

Qualquer coisa me avise.

**Comment by rdenadai** [comment]
Perfeito Erick, queria ter uma ideia de como estava o trabalho nela pra justamente fazer uma branch em cima disso.
Pois como falei vou fazer as alterações relativas a apresentação do DataFrame.

Farei isso amanhã.

Obrigado

**Comment by rdenadai** [comment]
Erick, fiz alguns testes e parece que a rotina que você criou para este exemplo esta funcionando.

O único ajuste no caso, seria gravar por cima os valores, caso a função pertença ao aluno e tenha o mesmo nome. Hoje esta adicionando novamente.

Os issues #20 e #22 estão feitos na branch resolving_issue_20 ... acabei por fazer um pouco mais na mesma branch.

**Comment by erickseolin** [comment]
Oi Rodolfo,

Bom trabalho. Se quiser pode fazer o pull request e aceitá-lo.
Vou fazer os ajustes restantes em breve.

Em 21 de julho de 2017 15:04, Rodolfo De Nadai <notifications@github.com>
escreveu:

**Comment by rdenadai** [comment]
Opa Erick... vou fazer mais alguns testes ainda hoje e depois faço isso. O pull request e merge.

Como falei as alterações que você fez estão funcionando muito bem... só esse ajuste que mencionei. Com relação ao restante acho que esta muito bom e atenderá perfeitamente ao que o Prof. nos pediu.

Até

**Comment by rdenadai** [comment]
@erickseolin , vi que você fez o merge das alterações referentes aos 3 issues os quais estávamos trabalhando (este e o outros dois que peguei para fazer)... chegou a fazer mais testes para validar também?
Vou testar a branch desenvolvimento para validar se esta tudo funcionando normalmente.

**Comment by erickseolin** [comment]
Sim, eu fiz o Merge, mas teve bastantes conflitos. Fiz alguns testes e tive
que corrigir algumas partes, mas me parece q agora está funcionando.
Eu não consegui criar o arquivo .csv, talvez essa parte não está
funcionando.

Em 15 de ago de 2017 20:50, "Rodolfo De Nadai" <notifications@github.com>
escreveu:

**Comment by rdenadai** [comment]
Ok, Erick, vou dar uma olhada na criação do arquivo .csv e lhe informo.
