### ISSUE TITLE
Diferenças entre os resultados gerados

### ISSUE THREAD

**Issue by rdenadai** [erickseolin/jn_tester#15]
Existe alguma diferença no resultado gerado entre o notebook do aluno e o tools/results-generator.py.
Caso ambos sejam executados, e ao executarmos o notebook do professor, é dado o erro:

> ValueError: Length mismatch: Expected axis has 15 elements, new values have 11 elements

**Comment by fabiocapsouza** [comment]
Acho que seria interessante ler com o pickle 1 arquivo .score de cada fonte e comparar. O número de testes foi o mesmo?

**Comment by rdenadai** [comment]
Talvez não tenha sido, entretanto os testes são gerados pelo professor.
É necessário avaliar melhor o problema. Se conseguir faço uma avaliação disso ainda hoje.

**Comment by rdenadai** [comment]
Realmente acho que o problema foi o levantado pelo @fabiocapsouza. 
Por default é gerado 5 TestCases usando o results-generator.py

Portanto, tavelz seja interessante colocar algum warning no momento do uso dele. Ou em outro momento.

Estou fechando este meu issue.
