### ISSUE TITLE
Não esta varrendo todos os diretórios na hora de montar a tabela.

### ISSUE THREAD

**Issue by rdenadai** [erickseolin/jn_tester#19]
Estou realizando um teste para tentar corrigir o problema do issue #15, entretanto me deparei com outro problema.

Ao criar subdiretórios dentro das pastas e gravar os testes nela, a função view_complete_table não esta conseguindo encontrar estes arquivos.

Ao usar /*/ ele busca apenas um nível abaixo da raiz onde estou procurando... se os arquivos estiverem um nível abaixo ainda ele não esta encontrando. Tendo de fazer algo do tipo /*/*/.

**Funciona com /*/:**
- aluno1
   - arquivo.test
- aluno2
  - arquivo.test

**Não esta encontrando com /*/:**
- aluno1
   - arquivo.teste
- aluno2
   - pasta1
       - arquivo.teste

Estou pensando em usar **os.walk**, para acertar isso.

Sugestões???

**Comment by fabiocapsouza** [comment]
Realmente. Uma opção é usar o os.walk, como vc sugeriu. No caso do Python 3.5+, é possível utilizar o glob passando a flag recursive=True e o padrão "**" no path para varrer múltiplos níveis de subdiretórios. Acho que ficaria mais versátil, pois continua tendo a opção de varrer apenas um nível se for desejado.

**Comment by rdenadai** [comment]
Boa @fabiocapsouza , vou fazer um teste usando o recursive=True do glob... Se não der certo, terá de ser o os.walk mesmo.

**Comment by rdenadai** [comment]
Opa, testei aqui... funcionou.

Coloquei recursive=True e um info para o professor caso ele não passe '/**/' no base_path que ele esta buscando.

**Comment by rdenadai** [comment]
Fix para este issue no PR: https://github.com/erickseolin/jn_tester/pull/21
