### ISSUE TITLE
Editar novo path para importar o jn_tester nos nootebooks.

### ISSUE THREAD

**Issue by erickseolin** [erickseolin/jn_tester#4]
A importação dos módulos ficou incorreta após a alteração do nome das pastas.

**Comment by rdenadai** [comment]
Onde esta acontecendo isso Erick?
Nos notebooks de exemplo eu até inclui a base do projeto no sys.path para não dar erro.

**Comment by rdenadai** [comment]
Já vi, estou fazendo os ajustes...

**Comment by rdenadai** [comment]
Relacionado ao PR: https://github.com/erickseolin/jn_tester/pull/6

**Comment by erickseolin** [comment]
OK
