### ISSUE TITLE
Remover bloco de usuario do arquivo  jn_tester/jn_tester/student/test.py

### ISSUE THREAD

**Issue by rdenadai** [erickseolin/jn_tester#5]
Erick, remover da branch develop o código da linha 23 até 36.
https://github.com/erickseolin/jn_tester/blob/develop/jn_tester/student/test.py#L23

Essa contribuição do Iván, eu combinei dentro da classe Execution.
https://github.com/erickseolin/jn_tester/blob/develop/jn_tester/student/models.py#L21

**Comment by erickseolin** [comment]
Modifique você mesmo, é melhor.
Crie um branch novo "fix_<algo>" do develop e modifique. depois pode dar merge no develop ou criar um pull request.

**Comment by rdenadai** [comment]
Feito... PR: https://github.com/erickseolin/jn_tester/pull/7

**Comment by erickseolin** [comment]
Rodolfo, depois recrie sua branch do develop, pq toda vez tenho que arrumar a mesma mudança em alguns arquivos que estão desatualizados na sua versão.

**Comment by erickseolin** [comment]
Fiz o merge das mudanças.

**Comment by rdenadai** [comment]
Vou recriar agora Erick... pode fechar esse issue.
